#!/bin/sh
# guildos-daemon-install.sh — POSIX shell installer for GuildOS daemon
# (task #1210, Hoping dm:c2e0f96a + Architect dispatch msg=f4ab7d01 +
# r3 design msg=98e1fdd1 + r4 schema fix per QA Gate3 BLOCK msg=b22dff9c +
# Challenger msg=60171380).
#
# Usage (via curl|bash from AddMachineModal "Connect" step):
#   curl -fL https://github.com/AivoGen/guildos-release/releases/latest/download/guildos-daemon-install.sh \
#     | bash -s -- --token <api_token> --core-url <core_ws_url>
#
# Phase 1 scope (Hoping ruling):
#   - Pipe-to-shell pattern (overrides design §1.5 no-pipe-to-shell)
#   - Detect-and-skip when daemon already installed AND running
#   - Long api_token passed via daemon CLI (--token / --core-url); daemon
#     persists its own canonical config.toml including runtime defaults
#     (claude/codex/gemini sections) via `config_persist::persist_minimal_config`
#   - User-mode install only; no sudo
#   - Linux x86_64 main path
#
# One-command onboarding flow (Architect r3 + QA r4 schema fix):
#   1. Download binary to canonical `~/.guildos/daemon/daemon`
#   2. `exec` daemon foreground with `--core-url` + `--token` flags.
#      Daemon's first-install bootstrap (Phase A-C #1024 + config_persist
#      #1047) takes over:
#        - Detects no canonical config at `~/.guildos/daemon/config.toml`
#        - Uses CLI args to start runtime
#        - Calls `persist_minimal_config` → writes canonical config.toml
#          with runtime defaults (so subsequent restarts don't need CLI)
#        - Inline Migrate releases embedded helper bytes from
#          `include_bytes!`, creates `versions/<v>/guildos-daemon` +
#          `daemon` symlink + `helper`, installs systemd user-unit,
#          hands off lifecycle to systemctl
#   3. User sees a single `curl|bash` complete + daemon registered.

set -eu

usage() {
    cat <<USAGE >&2
guildos-daemon installer

usage: $0 --token <api_token> --core-url <core_ws_url>

  --token       Long-lived daemon API token (generated by Core /api/daemons)
  --core-url    Core WebSocket URL the daemon connects to (e.g.
                wss://app.guildos.ai/ws/daemon)
USAGE
    exit 2
}

# ---- argv parsing (POSIX-safe, no getopt dependency) ----
TOKEN=""
CORE_URL=""
while [ $# -gt 0 ]; do
    case "$1" in
        --token)
            [ $# -ge 2 ] || usage
            TOKEN="$2"
            shift 2
            ;;
        --core-url)
            [ $# -ge 2 ] || usage
            CORE_URL="$2"
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            printf 'unknown argument: %s\n' "$1" >&2
            usage
            ;;
    esac
done

[ -n "$TOKEN" ] || { printf 'missing --token\n' >&2; usage; }
[ -n "$CORE_URL" ] || { printf 'missing --core-url\n' >&2; usage; }

# ---- platform detect (Phase 1 = Linux x86_64 only) ----
UNAME_S=$(uname -s)
UNAME_M=$(uname -m)
case "${UNAME_S}-${UNAME_M}" in
    Linux-x86_64)
        ASSET="guildos-daemon-linux-x86_64"
        ;;
    *)
        printf 'unsupported platform: %s-%s (Phase 1 supports Linux x86_64 only)\n' \
            "$UNAME_S" "$UNAME_M" >&2
        exit 3
        ;;
esac

# ---- canonical install paths (match design v2.5 §4.6.4) ----
DAEMON_DIR="$HOME/.guildos/daemon"
DAEMON_BIN="$DAEMON_DIR/daemon"
SYSTEMD_UNIT_NAME="guildos-daemon.service"

mkdir -p "$DAEMON_DIR"
chmod 700 "$DAEMON_DIR"

# ---- detect-and-skip (per Hoping + Architect r3) ----
# Re-run is a full no-op when daemon is already installed AND running.
# Future task can add a `--force` flag for token-rotation re-runs; for
# Phase 1, user removes the install dir and re-curls if needed.
daemon_running() {
    # systemd user-unit is the canonical lifecycle owner post-Migrate.
    if command -v systemctl >/dev/null 2>&1 \
        && systemctl --user is-active --quiet "$SYSTEMD_UNIT_NAME" 2>/dev/null; then
        return 0
    fi
    # Pre-Migrate or non-systemd fallback: live PID flock or pgrep match.
    if [ -f "$DAEMON_DIR/daemon.pid" ]; then
        existing_pid=$(cat "$DAEMON_DIR/daemon.pid" 2>/dev/null || echo "")
        if [ -n "$existing_pid" ] && kill -0 "$existing_pid" 2>/dev/null; then
            return 0
        fi
    fi
    if command -v pgrep >/dev/null 2>&1 \
        && pgrep -f "$DAEMON_BIN" >/dev/null 2>&1; then
        return 0
    fi
    return 1
}

if [ -e "$DAEMON_BIN" ] && daemon_running; then
    printf 'guildos-daemon already installed and running at %s — re-run skipped.\n' "$DAEMON_BIN"
    printf '(daemon self-update handles binary upgrades; the systemd user-unit owns lifecycle.)\n'
    exit 0
fi

# ---- download daemon binary (skip if already installed) ----
if [ ! -e "$DAEMON_BIN" ]; then
    DOWNLOAD_URL="https://github.com/AivoGen/guildos-release/releases/latest/download/${ASSET}"
    TMP_BIN=$(mktemp "${TMPDIR:-/tmp}/guildos-daemon.XXXXXXXX")
    trap 'rm -f "$TMP_BIN"' EXIT INT TERM HUP

    printf 'Downloading %s ...\n' "$ASSET"
    if ! curl -fL --proto '=https' --tlsv1.2 -o "$TMP_BIN" "$DOWNLOAD_URL"; then
        printf 'download failed from %s\n' "$DOWNLOAD_URL" >&2
        exit 4
    fi
    chmod +x "$TMP_BIN"
    mv "$TMP_BIN" "$DAEMON_BIN"
    trap - EXIT INT TERM HUP
    printf 'Installed daemon to %s\n' "$DAEMON_BIN"
else
    printf 'Daemon binary already present at %s — re-using.\n' "$DAEMON_BIN"
fi

printf 'Installing daemon (config + systemd user unit, no start) ...\n'

# #1316 (Hoping dm:144b9885 + Architect msg=c60523b1): install = setup
# only. The installer process must EXIT after persisting canonical
# config + installing the systemd user unit; the daemon is started by
# the user themselves so install.sh exiting (e.g. because it was piped
# from `curl | bash`) does not take the daemon down with it.
#
# `daemon run --install-only` is the entry point: it asserts non-root,
# persists canonical config.toml (via `config_persist::persist_minimal_
# config` with `PersistMode::OverwriteExplicitCli` — #1289-safe),
# installs the user unit at `$HOME/.config/systemd/user/guildos-
# daemon.service`, runs `systemctl --user daemon-reload + enable`
# (NO start), prints the next-start command, and exits 0. No `exec`
# here: install.sh is allowed to terminate normally afterward.
"$DAEMON_BIN" run --install-only --core-url "$CORE_URL" --token "$TOKEN"
